%%%
% File:         FitThermalAnisotropy.m
% Author:       Brycen Wendt (brycen.wendt@inl.gov; wendbryc@isu.edu)
% Date Created: 09/30/2015
%%%
% Syntax:       [kx,ky,Dx,Dy,Re] = FitThermalAnisotropy('subMat', 'xDir', 'yDir', 'filmMat')
% Inputs:       1) Name of substrate material, as it appears in Database.m
%               2) X-direction scan file name format
%               3) Y-direction scan file name format
%               4) Name of film material, as it appears in Database.m
%               5) Film thickness, in m
% Outputs:      1) kx, thermal conductivity of the substrate in x
%               2) ky, thermal conductivity of the substrate in y
%               2) Dx, thermal diffusivity of the substrate in x
%               2) Dy, thermal diffusivity of the substrate in y
%               3) Re, convolved spotsize of the pump and probe lasers
%%%
% Description:  This script is adapted from the sequence of files used to
%               fit data generated by the TCM to extract thermal properties
%               of the sample material. The author of these original files
%               is Dave Hurley (david.hurley@inl.gov):
%                   parmerror2.m
%                   loaddata.m
%                   TWM.m
%                   (ThermalAnisotropy).m
%
%               The purpose is to develop a computational method, using
%               2D Fourier Transforms, that will perform a minimization on
%               the data for an isotropic or anisotropic material.
%
%               The inputs are a sequence a files generated by the script
%               that runs the TCM. The files contain the following data:
%                   Name    Description
%                   AxPos   Axial position of the pump w.r.t. the probe
%                   mag     Magnitude of the signal measured by the probe
%                   phs     Phase of the signal measured w.r.t. the source
%%%

function [thermalConductivityX, thermalConductivityY,...
          thermalDiffusivityX, thermalDiffusivityY,...
          spotSize] = ...
    FitThermalAnisotropy(substrateMaterial,...
                         xDirectionFileFormat, yDirectionFileFormat,...
                         filmMaterial, filmThickness)
    % Get the initial properties
    database = Database();
    substrateProperties = database.GetThermalProperties(substrateMaterial);
    filmProperties = database.GetThermalProperties(filmMaterial);
    
    % Seet the initial values
    thermalConductivityX = substrateProperties.k;
    thermalConductivityY = thermalConductivityX;
    thermalDiffusivityX = substrateProperties.d;
    thermalDiffusivityY = thermalDiffusivityX;
    spotSize = database.GetSpotSizeFromMagnification(50);
end
